apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sara-sap
  description: API to enable reporting of results from robot acquired data analysis to SAP. 
  annotations:
    github.com/project-slug: equinor/sara-sap
    github.com/team-slug: equinor/eq-robot-developer
spec:
  type: service
  owner: group:default/eq-robot-developer
  system: system:default/flotilla
  lifecycle: experimental
  dependsOn:
    - component:sara
